### ISSUE TITLE
can't use dylibs dyld overlapping segments

### ISSUE THREAD

**Issue by ghost** [antons/dyld-shared-cache-big-sur#6]
hello,

do you know how to fix it?

**Comment by antons** [comment]
> I'm on catalina, i copied big cache from big sur, use your program and trying to use ChatKit Private Framework but i'm getting an error: overlapping segments from dyld.. any idea how to fix this?

The libraries extracted by this project are not executable. You could probably achieve this with a lot of work, see more here: https://worthdoingbadly.com/dscextract/. I only ported some of the modifications to make it run in Hopper.

**Comment by ghost** [comment]
> > I'm on catalina, i copied big cache from big sur, use your program and trying to use ChatKit Private Framework but i'm getting an error: overlapping segments from dyld.. any idea how to fix this?
> 
> The libraries extracted by this project are not executable. You could probably achieve this with a lot of work, see more here: https://worthdoingbadly.com/dscextract/. I only ported some of the modifications to make it run in Hopper.

sorry,  you mean executable? i am trying to run program that call those functions externally, i look at the link but not really understand what to change.
can you steps on doing it maybe?

also, the error comes from dyld, https://opensource.apple.com/source/dyld/dyld-360.21/src/ImageLoaderMachO.cpp
do you know if lower the address will fix the problem?

thank yu so much for answering

**Comment by antons** [comment]
It’s impossible to run libraries extracted by this project. https://worthdoingbadly.com/dscextract/ details all the specific things you need to do to make them executable, but it’s probably not worth doing that. Please read the entire article in detail, especially the epilogue. I’m sorry, but I cannot help you further.
